version: 2

models:
  - name: aw_query
    description: tls count of unique users
    columns:
      - name: user_pseudo_id
        tests:
          - not_null
      
      - name: centre
        tests:
          - accepted_values:
              values: ['tls']
